version: '3.8'

services:
  backend:
    build: ./backend
    container_name: restorapp-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:restordb
      - APP_JWT_SECRET=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
    networks:
      - restorapp-network

  frontend:
    build: ./frontend
    container_name: restorapp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - restorapp-network

networks:
  restorapp-network:
    driver: bridge
